##############################################################
# CALIBO API AUTOMATION FRAMEWORK CONFIGURATION
##############################################################

##############################################################
# Environment
##############################################################

environment=QA

##############################################################
# Application URLs
##############################################################

base.url=https://accelerate-qa.calibo.com
login.url=https://accelerate-qa.calibo.com

##############################################################
# Authentication
##############################################################

username=api.automation@calibo.com
password=H2u82a^WA&jn

##############################################################
# Tenant
##############################################################

tenant.name=Automation
tenant.id=Tenant296388

##############################################################
# Browser Configuration
##############################################################

browser=chrome
headless=false

##############################################################
# Playwright Configuration
##############################################################

explicit.wait=60
page.load.timeout=120

##############################################################
# API Configuration
##############################################################

content.type=application/json

##############################################################
# Retry Configuration
##############################################################

retry.count=2
retry.interval=3000

##############################################################
# Framework Configuration
##############################################################

console.logs=true
capture.request=true
capture.response=true

##############################################################
# Test Data
##############################################################

test.data.path=resources/
users.json=users.json

##############################################################
# Optional Proxy (Leave blank if not used)
##############################################################

proxy.host=
proxy.port=

##############################################################
# Execution
##############################################################

parallel=false
thread.count=1
